[package]
name = "bettertest-frontend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bettertest-frontend"
path = "src/main.rs"

[dependencies]
bettertest-shared = { path = "../shared" }
gloo = "0.12"
gloo-net = { version = "0.7", features = ["json"] }
wasm-bindgen-futures = "0.4"
yew = { version = "0.23", features = ["csr"] }
