openapi: 3.2.0
info:
  title: bettertest worker API
  description: API exposed by bettertest worker nodes. all responses are SSE streams—no polling.
  version: 0.1.0

paths:
  /run:
    post:
      summary: run a command in a container
      description: |
        starts a container from the given image, runs the command, and streams
        events back via SSE. the response is a text/event-stream that stays open
        until the job finishes. the caller does not need to make any further
        requests—the worker pushes all events.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunRequest'
            example:
              image: soundscrape-test
              command: "pytest -v test/test_spotify.py"
      responses:
        '200':
          description: SSE stream of job events
          content:
            text/event-stream:
              schema:
                type: string
              examples:
                full_run:
                  summary: typical successful run
                  value: |
                    event: started
                    data: <container_id>

                    event: log
                    data: collecting tests...

                    event: log
                    data: warning: something

                    event: done
                    data: 0

components:
  schemas:
    RunRequest:
      type: object
      required:
        - image
        - command
      properties:
        image:
          type: string
          description: docker image to run the command in
        command:
          type: string
          description: command to execute in the container (passed to sh -c)
