openapi: 3.1.0
info:
  title: bettertest worker API
  version: 0.1.0
paths:
  /health:
    get:
      responses:
        '200':
          description: plain text
          content:
            text/plain; charset=utf-8: {}
  /run:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunRequest'
        required: true
components:
  schemas:
    RunRequest:
      type: object
      properties:
        command:
          type: string
        image:
          type: string
      required:
      - image
      - command
