[package]
name = "bettertest"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["http1", "json", "tokio"] }
rust-embed = "8.11.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "process", "io-util"] }
tokio-stream = "0.1.18"
